### ISSUE TITLE
sfc - Stateless Function Component

### ISSUE THREAD

**Issue by bulentala** [ijsto/reactnextjssnippets#1]
sfc does not work

![Ekran Resmi 2019-11-05 18 24 55](https://user-images.githubusercontent.com/46373855/68220944-aa437d00-fff9-11e9-9ac9-d9ac65deb4c3.png)
![Ekran Resmi 2019-11-05 18 22 31](https://user-images.githubusercontent.com/46373855/68220954-afa0c780-fff9-11e9-91d2-7b52f25248b4.png)

**Comment by ScottAgirs** [comment]
Hey @bulentala, thanks for reporting this. The proper snippet definition is [`fc`](https://github.com/ijsto/reactnextjssnippets#fc---functional-component-without-a-state). The spelling error has been fixed. I will now close this, feel free to open the issue if something doesn't work as expected.

**Comment by bulentala** [comment]
hey Scott

Thanks for this snippets.

getInitialProps snippet would be very useful...

Bestregards

Bülent ALA

Scott Agirs <notifications@github.com>, 5 Kas 2019 Sal, 20:21 tarihinde
şunu yazdı:
