### ISSUE TITLE
Check for Next.js 10 Image component snippets for TypeScript

### ISSUE THREAD

**Issue by ScottAgirs** [ijsto/reactnextjssnippets#10]
With v1.6.0 we've added JavaScript snippets for the new Image tag.

We have not checked for TypeScript availability and/or addition.

@Nnadozie would you be interested in giving this a quick look/potentially adding missing? 🙌

**Comment by Nnadozie** [comment]
Sure thing @ScottAgirs!

**Comment by ScottAgirs** [comment]
Added with #11
