### ISSUE TITLE
faulty README descriptor for ccgipaq [gipaq = ccgip]

### ISSUE THREAD

**Issue by bulentala** [ijsto/reactnextjssnippets#3]
![Ekran Resmi 2019-11-12 06 45 48](https://user-images.githubusercontent.com/46373855/68640303-5a444900-0518-11ea-86f8-1af4ac57f1c3.png)
![Ekran Resmi 2019-11-12 06 46 15](https://user-images.githubusercontent.com/46373855/68640304-5adcdf80-0518-11ea-88a8-6cf72d9155be.png)
![Ekran Resmi 2019-11-12 06 44 43](https://user-images.githubusercontent.com/46373855/68640305-5adcdf80-0518-11ea-8b8e-82d8167beac3.png)
![Ekran Resmi 2019-11-12 06 45 11](https://user-images.githubusercontent.com/46373855/68640306-5b757600-0518-11ea-8701-2237fb08a03c.png)
![Ekran Resmi 2019-11-12 06 45 28](https://user-images.githubusercontent.com/46373855/68640308-5b757600-0518-11ea-8526-9a14a8250f37.png)

**Comment by ScottAgirs** [comment]
Hey @bulentala, thank you for reporting this.

I have corrected the title, in the future, please include more details and description about the issue, if possible :)

The readme will be updated with the next release, very soon.

Also please confirm I have found the right issue.
I will close this for now, feel free to open if necessary
