### ISSUE TITLE
getServerSideProps / getStaticProps snippets?

### ISSUE THREAD

**Issue by Dannymx** [ijsto/reactnextjssnippets#5]
For a more granular approach now there's these two methods, can we add them?

**Comment by ScottAgirs** [comment]
Hey @Dannymx thanks for opening an issue for this! Would you consider creating a PR for it? If not I can try to get this rolled out next week

**Comment by ScottAgirs** [comment]
Hey @Dannymx, did a quick update - your requested snippets + `getStatisPaths()` is now available with [v1.4.1](https://github.com/ijsto/reactnextjssnippets/releases/tag/v1.4.1). Feel free to update your extension (reload VS Code) and should be good to go! :)

I will close this for now, feel free to re-open, if something's broken.

Thank you for the suggestion!
