### ISSUE TITLE
create snippet-ts.json containing typescript equivalents for snippets

### ISSUE THREAD

**Issue by Nnadozie** [ijsto/reactnextjssnippets#8]
I noticed gsp, the snippet I'm particularly interested in doesn't have a typescript equivalent.

I propose creating a snippets-ts.json file that clones snippets.json where the ts equivalents can be added, as done in [reactsnippets](https://github.com/RunningCoderLee/reactsjs-snippets/blob/master/package.json)

If you agree with this proposal, I'll make a pr with the ts equivalets in snippets-ts.json.

**Comment by ScottAgirs** [comment]
@Nnadozie yeah, that would be cool! Let's do it 🚀 🙂

**Comment by Nnadozie** [comment]
Awesome! I'll get to work on it \^_^/

**Comment by ScottAgirs** [comment]
Closing as per @Nnadozie PR #9. Thank you for the PR!
